### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by StummeJ** [danielmcconville/gist-sync-file-action#27]
While running a github workflow we're receiving the following message:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: danielmcconville/gist-sync-file-action@v1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by danielmcconville** [comment]
Thanks @StummeJ.
